### ISSUE TITLE
self.close not supported

### ISSUE THREAD

**Issue by bengillies** [nolanlawson/pseudo-worker#12]
According to MDN there should be a `close` method on self which closes the web worker.

As far as I can tell, this is missing.

I suppose it should do the same thing as `terminate`, but from inside the worker itself.

**Comment by nolanlawson** [comment]
this is not implemented yeah

**Comment by bengillies** [comment]
Is it as simple as aliasing close to the terminate function on workerSelf [here](https://github.com/nolanlawson/pseudo-worker/blob/master/index.js#L145)?

I'm happy to open a PR if you want it.

**Comment by nolanlawson** [comment]
I'm not sure what the exact semantics are, but if you add a change with a test that passes then sure thing I'll accept a PR. :smiley:

**Comment by roysudi** [comment]
@nolanlawson Using pseudo-worker to invoke REST services with rxjs interval. Hence, cleanup becomes imperative. Calling terminate() doesn't close things up as it does in case of native web worker. 
Any suggestions how to kill specific api call?

**Comment by roysudi** [comment]
@nolanlawson Nevermind, I worked my way out of it using rxjs takeUntill & a postMessage with data indicating a terminate. However, a self.close/terminate mimicking the native would be great addition to an awesome polyfill! :)

**Comment by bengillies** [comment]
Took me a while to get around to this, but I've added a `self.close` in PR #13.

It's not a 1-1 mapping with the proper web worker API (that is, it won't stop any code from running) but then the `worker.terminate` method doesn't either and I'm not sure that's possible to shim anyway.

It _does_ prevent doing `postMessage` from both inside and outside the worker though.

Let me know if there's anything else that needs doing to it.

**Comment by nolanlawson** [comment]
fixed in #14
