### ISSUE TITLE
Vue Cli 3x error: Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ngohuunam** [nolanlawson/pseudo-worker#17]
Hi, I taked a Screenshot from chrome console
![pseudo-worker-error](https://user-images.githubusercontent.com/3610240/48684442-2f186980-ebe4-11e8-9042-472386d51e87.jpg)
Anyway to fix this
Thanks

**Comment by nolanlawson** [comment]
Check the Network tab in DevTools. Probably your web worker URL endpoint is returning a 404 or an HTML page.

**Comment by nolanlawson** [comment]
Please reopen if this is a true bug in pseudo-worker. Thanks! :)
