### ISSUE TITLE
Messages order should be FIFO

### ISSUE THREAD

**Issue by titoasty** [nolanlawson/pseudo-worker#8]
Hi,

There is a bug with messages orders.
When we post a message, the message is pushed to postMessageListeners.
But when they are executed, next message is popped, which means LIFO !
It definitely has to be FIFO, or execution order is not correct (I actually had the case)

To fix, just replace "pop" by "shift" on line 151 and it's all good !

(oh and thanks for the library, it saved me and my code some hours and problems :) )

**Comment by nolanlawson** [comment]
Per the web worker spec, messages are supposed to be FIFO. Which browser are you seeing this on?

**Comment by nolanlawson** [comment]
Oh I see what you mean. You mean I should change [this line](https://github.com/nolanlawson/pseudo-worker/blob/06ee04ed2968226ca1c811b2c208f2ec100cae65/index.js#L151)? I think you may be write. I need to find a test case though and compare it against the browser implementation.

**Comment by titoasty** [comment]
Yes definitely !

By using push... then pop, it's a LIFO case.
By by using push... then shifts, it's FIFO :)

For a test case, you could push multiple messages then execute them.
Now, they are in reverse order, but with the fix they will be in FIFO order.

Oh and the browser is Chrome 50 on Ubuntu 16.04.

**Comment by nolanlawson** [comment]
fixed in v1.1.1
